on: 
  release:
      types: [published]
  workflow_dispatch:
  
jobs:
  documentation:
    name: Publish documentation
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Clone docs repo
        run:
          git clone https://github.com/A-Good-System-for-Smart-Cities/kite-utils-docs
      - name: Generate Docs
        run: |
          pip install -e .
          pip install pdoc
          pdoc --t doc_template --docformat numpy -o kite-utils-docs KiTE/.
      - name: Push docs to doc repo
        uses: cpina/github-action-push-to-another-repository@main
        with:
          source-directory: 'kite-utils-docs'
          destination-github-username: 'A-Good-System-for-Smart-Cities'
          destination-repository-name: 'kite-utils-docs'
          target-branch: main
